### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by aoi1** [womenengjp/womeneng.jp#20]
Emptyよりは何かかわいいfaviconにしたい！（タブでわかりやすいし）
本当は誰かに頼んでかわいいやつ作ってもらいたいところですが、ひとまず仮でなにか入れておきたいです。
@chaspy 何か色のイメージとかありますか？

https://favicon.io/favicon-generator/
これを使って簡単に作れる範囲で作りたいと思います。

**Comment by aoi1** [comment]
![favicon-32x32](https://user-images.githubusercontent.com/16409583/106071153-2e2add00-6149-11eb-8f33-bd0e9f89905b.png)

**Comment by aoi1** [comment]
![favicon-32x32](https://user-images.githubusercontent.com/16409583/106071255-5ca8b800-6149-11eb-8798-17a43865c3c5.png)
丸いのも可愛い

**Comment by chaspy** [comment]
丸いの可愛い！favicon-generator なんて便利なものが。。。！
特に色のイメージは持ってないのでおまかせします！
