### ISSUE TITLE
サイトトップページにgithub.comリポジトリへのリンクを貼りたい

### ISSUE THREAD

**Issue by aoi1** [womenengjp/womeneng.jp#42]
よくトップページにgithub.comのアイコンが貼ってあって、
クリックするとリポジトリに飛べる、みたいなやつ。
お月様アイコンの隣あたりが良さそう。

**Comment by chaspy** [comment]
Font Awesome のGitHub がなぜか前見れなかったんですよね。お月様の隣で再チャレンジする。
https://fontawesome.com/icons/github?style=brands
