### ISSUE TITLE
womeneng.jp のロゴが欲しい

### ISSUE THREAD

**Issue by chaspy** [womenengjp/womeneng.jp#56]
@aoi1 さんがイメージを書く！
誰かが書いてくれることを待つ！

**Comment by 515hikaru** [comment]
通りすがりで要件とかわかってないですが、自動生成でもよければ下記のサイトは個人的によく使ってます。
（自動生成ではいけない理由とか信条とかあればすみません。。）
https://hatchful.shopify.com/ja/

**Comment by aoi1** [comment]
@515hikaru おおお！！！ありがとうございます！！こちらのサービス全く知りませんでした！！
今回の要望にとてもマッチしていそうですね🙏ありがとうございます活用させていただきます🙏

**Comment by aoi1** [comment]
https://hatchful.shopify.com/ja/terms
terms of serviceを読んでから利用するか決める。
デザイン自体はめちゃめちゃよさそう！

**Comment by aoi1** [comment]
![スクリーンショット 2021-02-11 20 41 14](https://user-images.githubusercontent.com/16409583/107632190-82859f00-6ca9-11eb-9e00-7cd0ce45e1ad.png)

@chaspy いくつか作ってみましたがどれがいいとかありますか？

**Comment by chaspy** [comment]
どれも素敵です！あえて投票するなら僅差で左上のベージュのやつがシンプルでシュッとしていて好きです！

**Comment by aoi1** [comment]
ベージュのやつにします！
